Added a struct to hide the output of a std::cin
nxxm/cli_widgets pull request #2
Opened 2021-09-14 08:49 UTC by Lambourl

2021-09-14 09:48 UTC, daminetreg requested changes

2021-09-14 09:48 UTC, daminetreg commented on cli_widgets/stdin_hide_guard.hpp
> +#endif
Well the implementation before with a central function that you could pass true and false  was cleanier. I mean you could call the function inside the RAII wrapper.

2021-09-14 09:48 UTC, daminetreg commented on cli_widgets/stdin_hide_guard.hpp
> +#endif
It's just a matter of oring/xoring the ECHO flag, then the code can be divided by half in size.

2021-09-14 09:48 UTC, daminetreg commented on cli_widgets/stdin_hide_guard.hpp
> +  struct stdin_hide_guard {
Perhaps adding a brief to document  the purpose  would be cool

2021-09-14 10:52 UTC, Lambourl commented
I thought that for the RAII, I had to have a destroyer which returns to the initial state

2021-09-14 10:53 UTC, Lambourl commented
I think I understood the structure is only a wrapper

2021-09-14 11:30 UTC, daminetreg commented
Could you add : 
- [ ] an example usage in an examples/ folder
- [ ]  a documentation comments on the class 
- [ ] pull master to have the CI run through

?

2021-09-15 13:09 UTC, daminetreg commented on .nxxm/deps
> +  ,"platform" : [ "Boost::thread", "Boost::system", "Boost::filesystem", "Boost::regex" ]
We don't need them here.

2021-09-15 14:27 UTC, daminetreg approved these changes

2021-09-15 14:30 UTC, daminetreg commented
I believe hidden_input_guard is finally the best name for this

2021-09-16 11:54 UTC, daminetreg approved these changes
Thanks ! 👍

2021-09-16 11:54 UTC, merged